### ISSUE TITLE
No such property: ossrhUsername for class

### ISSUE THREAD

**Issue by randohinn** [SudoPlayGames/Joise#7]
Gradlew.bat gives me this:

```
> No such property: ossrhUsername for class: org.gradle.api.publication.maven.in
ternal.ant.DefaultGroovyMavenDeployer
```

**Comment by codetaylor** [comment]
Ok. I'm going to leave this here and dig into this issue soon.

http://stackoverflow.com/questions/17311070/gradle-how-to-share-a-build-gradle-which-contains-information-i-am-the-only-one

**Comment by codetaylor** [comment]
I'm not very familiar with Gradle and Maven, so please bear with me.

After checking out [this](http://stackoverflow.com/questions/17311070/gradle-how-to-share-a-build-gradle-which-contains-information-i-am-the-only-one) and [this](https://docs.gradle.org/current/userguide/signing_plugin.html), it looks like I don't get the error because I have a file `${USER}/.gradle/gradle.properties` which specifies the `ossrhUsername` and `ossrhPassword` variable that is used by the `uploadArchives` task in the file `build.gradle`.

A temporary solution would be to create your own `${USER}/.gradle/gradle.properties` file and in the file, create the properties that are missing, but leave the values empty:

```
ossrhUsername=
ossrhPassword=
```

I'm not sure about the best way to fix this in the repo yet.

**Comment by RossKinsella** [comment]
I had the same problem as @randohinn

Adding the gradle.properties file was the fix

Thanks @codetaylor

**Comment by randohinn** [comment]
Dummy gradle.properties seems to be OK. Should be mentioned somewhere, though.

**Comment by codetaylor** [comment]
I agree, it should be clarified somewhere.

So if I understand [the gradle.properties file](https://docs.gradle.org/current/userguide/build_environment.html) correctly, I can specify the dummy properties in a gradle.properties file in the repo which would then be overridden with the gradle.properties file in the user's home directory.

I will fix this soon, bump the version ever so slightly and re-deploy the patched one to maven.

**Comment by codetaylor** [comment]
On second thought, this issue only applies if you're cloning the repo and building it yourself and doesn't really apply if you're using the lib via maven. I guess I don't need to re-deploy after all... oh well.
