### ISSUE TITLE
multithreaded?

### ISSUE THREAD

**Issue by sreich** [SudoPlayGames/Joise#8]
is this library multithreaded/thread safe, and which parts? the original library, accidental noise is threadable afaik.

**Comment by codetaylor** [comment]
That's a really good question, Shaun. I don't remember giving it a lot of thought and it's been a while since I've been into the code. At a cursory glance through some of the modules, I'm going to have to venture a guess, err on the side of caution, and say no, it isn't thread safe. Ideally, I'd like to spend time identifying the parts that aren't thread safe, possibly with better tests (or tests at all for that matter), and either adapting them to be thread safe or documenting that they aren't thread safe and why. Realistically, I just don't have that time right now.

I think the safest way to approach threading with this library right now would be to generate an instance of the module chain in each thread, since, at least in theory anyway, identical chains with identical seeds should produce the same results.

**Comment by sreich** [comment]
ah good idea, i split my method up into creating lots of modules, chaining them with the same seed, and do the same for n threads..greatly sped things up, and no issues, since i partitioned my map size into n parts and had each thread work on its own section.
